### Health
@name = Health
@details = Check API availability and dependency health.

### Environment Variables
@HOST={{base_url}}
@AUTH_HEADER=Authorization: Bearer {{api_key}}

### fast 🏎️: API is live or not
# @name Healthz
GET {{HOST}}/healthz

### slow 🐢: Checks all its dependencies: DBs, Node RPC, ..
# @name HealthCheck
GET {{HOST}}/health
{{AUTH_HEADER}}