### Wallet API — Manage & View Balances
@name = Wallet
@details = View balances of assets across chains.

### Environment Variables
@HOST= {{base_url}}
@USER_ID={{user_id}}
@AUTH_HEADER = Authorization: Bearer {{api_key}}

###
# @name Health
GET {{HOST}}/healthz

### 
# @name FetchPreOcpNetBalance
@CHAIN=Sepolia
@COIN=USDT
GET {{HOST}}/payment/onchain/net_balance/{{USER_ID}}/{{CHAIN}}/{{COIN}}
{{AUTH_HEADER}}

###
# @name FetchPreOcpTotalEstFees
@CHAIN=Sepolia
@COIN=USDT
GET {{HOST}}/payment/onchain/est_fee/{{USER_ID}}/{{CHAIN}}/{{COIN}}
{{AUTH_HEADER}}

###
# @name FetchPreOcpBalanceAndEstFees
@CHAIN=Sepolia
@COIN=USDT
GET {{HOST}}/payment/onchain/balance_est_fees/{{USER_ID}}/{{CHAIN}}/{{COIN}}
{{AUTH_HEADER}}

###
# @name RequestFaucet
@CHAIN=Sepolia
@COIN=USDT
POST {{HOST}}/faucet/{{USER_ID}}/{{COIN}}/{{CHAIN}}
{{AUTH_HEADER}}

###
# @name GetWalletBalancesByChain
@CHAIN=Sepolia
GET {{HOST}}/wallet/balances/by_chain/{{USER_ID}}/{{CHAIN}}
{{AUTH_HEADER}}

###
# @name GetWalletBalancesByCoin
GET {{HOST}}/wallet/balances/by_coin/{{USER_ID}}/{{COIN}}
{{AUTH_HEADER}}